### ISSUE TITLE
Issue Configuring

### ISSUE THREAD

**Issue by RobertoHernandezjr** [djsplice/SCS#4]
Tried setting up and got error I don't remember what it was but I think it has to do with the macro, I went ahead and just set it to generic fan and used  static airflow for now.  Curious what the advantage of using set pin vs generic fan, aslo SET_FAN_SPEED FAN=Bed-Blower-L SPEED=0.5 works since its a fan now.

**Comment by djsplice** [comment]
Apologies - I didn't have email notifications setup on this repo!

Good question on the generic fan vs output pin - I think either should work, but you get some better options with generic fan.  I'll update the examples to reflect that! Thanks for the suggestion.

**Comment by djsplice** [comment]
```
[fan_generic Bed-Blower-R]
# BED BLOWER RIGHT
pin: PD12
max_power: 1.0
shutdown_speed: 0
off_below: 0.0
kick_start_time: 0.100

[fan_generic Bed-Blower-L]
# BED BLOWER LEFT
pin: PD13
max_power: 1.0
shutdown_speed: 0
off_below: 0.0
kick_start_time: 0.100

[gcode_macro BED_BLOWER]
gcode:
    # Use a default fan speed to off - expecting an INT as input
    {% set S = (params.S)|default(0)|float %}
    {% if S > 0 %}
        {% set S = (S/100) %}
    {% endif %}
   SET_FAN_SPEED FAN=Bed-Blower-R SPEED={S} 
   SET_FAN_SPEED FAN=Bed-Blower-L SPEED={S}

[gcode_macro M106]
rename_existing: M106.1
gcode:
  M106.1 { rawparams }
  {% set bed_blower_speed = params.S|float * 100/255 %}
  SET_FAN_SPEED FAN=Bed-Blower-R SPEED={ bed_blower_speed/100 }
  SET_FAN_SPEED FAN=Bed-Blower-L SPEED={ bed_blower_speed/100 }
```
